sudo: false
language: python

env:
  global:
    # Doctr deploy key for turboscholz/blog
    - secure: "SW+5zr8zddYlnA4g7AmLw+UIMJ4gNzD8V0cABcD1ZHfeO8V9Fa4WzVeasfwOyk2IPdObKcQ+ncVXW5uZ2dix5W9nZrPnfZ46Yj5/g+bgsTi/7iqV396n0cJ6LL5pDx7Hw58KVLhQzY3rqby515+yPN1+FQ/axQEyAkC/a/cXWF6zG/SIaZigbnrbDbaP4dKEckNm5IfLVW/qgofpqhLwnMSfPe6PpC8L9d13Ti+Q3WqSU9zRajHwLjw4CN0DfkqCRXyDUi1pqlXgWfmLCjJ3kkgTnabz4vyJXHElFWNTm7ZpxnGkymbzAJzDp8SurCrB4UgFmONRkX/qnjLVfoeb9T9L4p6PqL4eEEhPagLKXmO9c2o8BeUlvWzLbgVD1yZdAa7/DVOUPi2MlkmyxRMZloym3bfYteD5UGuQA4mvrtD6HE01gVaSBZNrQ1sA0xvqNnWGXkQ5BYdxar4Mrzox8jhftkyJ/xP/hB7GWChFiMehZ5W+/qbCktW9NoscWrKawQk+oDHJo+nLJ13erDJjcXAGBaWrguFhuJh+AbJdPk8UCm0Z15WXRwFjf7ISR9hvIlL0UdXylvNaXjcG73Px34AtU+9+caLc0/06sojCT6CPawmRwBGGZmdea4pzzF2Pc8QRy1qcuFrJ78D2l39PfufzjkHpJ8JzF0pMmIW2jD4="

python:
  - 3.6

install:
  - pip install "Nikola[extras]" doctr
  - nikola theme -i bootstrap3

script:
  - set -e
  - nikola build
  - doctr deploy . --built-docs output/
